### ISSUE TITLE
Remove FloppyBot specific configuration.

### ISSUE THREAD

**Issue by MarvelousAnything** [Discord4Spring/Discord4Spring#12]
[discord4spring] src/main/resources/application.yml (Lines 1-17)

```

server:
  port: 0
hypixel:
  token: ${HYPIXEL_API_TOKEN:YOURTOKENHERE}
bot:
  token: ${FLOPPY_BOT_TOKEN:YOURTOKENHERE}
  embed:
    title: "-SP3CTR3 BOT-"
    description: "This is in BETA - DM Yoursole1#7254 with issues"
    color: 2871056
    thumbnail:
      url: "https://cdn.discordapp.com/attachments/826929655851384922/852204578064564254/a_3596d9dbe4464e2d1cb9265d8ceb3ccf.png"
    footer:
      text: "Created with \u2665 by Yoursole1#7254"
logging:
  level:
    root: info
```

[Open in IDE](https://api.codestream.com/c/YDGPCsiGWQF2P-yx/I6kl3q5bSau46ZblwzMPlg?marker=60cfcafe88d0b06068c92b2a&ide=default&src=GitHub) · [Open on GitHub](https://github.com/discord4spring/discord4spring/blob/6eaf29f3e83cd93b008958c28033d8e31ec97f69/src/main/resources/application.yml#L1-L17)

<sup>Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=issue&utm_campaign=github)</sup>
